whitelist_rules:
excluded: # paths to ignore during linting. Takes precedence over `included`.
- Carthage
- Pods
- vPlay/ThirdParties
- vPlay/Helper/BMPlayer
# rules that have both warning and error levels, can set just the warning level
# implicitly
line_length: 150
# they can set both implicitly with an array
reporter: "checkstyle" # reporter type (xcode, json, csv, checkstyle)
